#!/usr/bin/env sh
set -eu

export XDG_CURRENT_DESKTOP=XMonad
export XDG_SESSION_DESKTOP=xmonad

if [ -f "$HOME/.Xresources" ]; then
  xrdb -merge "$HOME/.Xresources"
fi

setxkbmap de -option caps:escape
feh --bg-fill ~/.local/share/wallpapers/gruvnode.jpg &
exec xmonad
