font_family JetBrains Mono
font_size 11.0

background #1d2021
foreground #ebdbb2
cursor #ebdbb2
selection_background #504945
selection_foreground #fbf1c7

background_opacity 0.8
dynamic_background_opacity no

scrollback_lines 10000
enable_audio_bell no
